server:
  port: 50051
  host: "0.0.0.0"
database:
  maxsize: 1000000
  gcinterval: "5m"
wal:
  directory: "/var/lib/kvstore/wal"
  syncinterval: "100ms"
master:
  slaveaddresses:
    - "localhost:50052"
  syncinterval: "10s"
  batchsize: 100