master:
  server:
    port: 50051
    host: "0.0.0.0"
  database:
    maxsize: 1000000
    gcinterval: "2m"
  wal:
    directory: "../wal/master"
    syncinterval: "100ms"
  slaveaddresses:
    - "localhost:50052"
    - "localhost:50053"
  syncinterval: "10s"
  batchsize: 100
slave:
   server:
     host: "0.0.0.0"
   database:
     maxsize: 1000000
     gcinterval: "2m"
   wal:
     directory: "../wal/slave"
     syncinterval: "100ms"
env: local